env:
  browser: true
  es6: true
  node: true
extends:
  - airbnb
  - prettier
  - prettier/react
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - prettier
  - react
  - react-hooks
rules:
  prettier/prettier: error
  react/jsx-filename-extension: off
  react-hooks/rules-of-hooks: "error"
  react-hooks/exhaustive-deps: "warn"
